@startuml
actor "Port Manager" as Adm
participant ":WarningWarehouseCapacityUI" as System
participant ":WarningWarehouseCapacityController" as SSC
participant ":US307" as us
participant ":FileOperation" as f

autonumber

activate Adm

Adm -> System: wish to know if the warehouse have available capacity to accommodate the new manifest

activate System

System --> Adm: request the cargo manifest id and the warehouse id

deactivate System

Adm -> System: types requested data

activate System

System -> SSC: createUS307

activate SSC

SSC -> us: demo(cargo_manifest_id, warehouse_id)

activate us

us -> us: initialize

us -> f: WriteToAFile(path, data)

deactivate us

activate f

f --> SSC: file

deactivate f

SSC --> System: file

System --> Adm: shows the requested data

deactivate SSC

deactivate System

deactivate Adm
@enduml